@extends('pos.layout.app')

@section('content')
<div class="flex-1 overflow-y-auto bg-slate-50 p-4 md:p-6">
    <div class="max-w-5xl mx-auto space-y-5">
        <div class="flex items-center justify-between gap-4"><div><a href="{{ route('pos_product.orders') }}" class="text-sm text-[#128C7E] hover:underline"><i class="fas fa-arrow-left mr-1"></i>Store Orders</a><h1 class="text-2xl font-bold text-slate-800 mt-2">{{ $order->order_number }}</h1><p class="text-sm text-slate-500 mt-1">Created {{ $order->created_at->format('d M Y, h:i A') }}</p></div><span class="px-3 py-1.5 rounded-full bg-blue-50 text-blue-700 text-sm font-semibold">{{ ucfirst($order->status) }}</span></div>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-5"><div class="bg-white rounded-2xl border border-slate-200 shadow-sm p-5"><p class="text-xs font-semibold text-slate-400 uppercase">Destination Store</p><p class="text-lg font-bold text-slate-800 mt-2">{{ optional($order->store)->name ?? '-' }}</p><p class="text-sm text-slate-500 mt-1">{{ optional($order->store)->address ?? '' }}</p></div><div class="bg-white rounded-2xl border border-slate-200 shadow-sm p-5"><p class="text-xs font-semibold text-slate-400 uppercase">Created By</p><p class="text-lg font-bold text-slate-800 mt-2">{{ optional($order->posUser)->name ?? '-' }}</p><p class="text-sm text-slate-500 mt-1">{{ optional($order->posUser)->email ?? '' }}</p></div></div>
        <div class="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden"><div class="p-5 border-b border-slate-200 flex justify-between items-center"><div><h2 class="text-lg font-bold text-slate-800">Order Items</h2><p class="text-xs text-slate-400 mt-1">Products requested for this store.</p></div><span class="px-3 py-1.5 rounded-full bg-emerald-50 text-[#128C7E] text-xs font-semibold">{{ $order->items->count() }} Items</span></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-50"><tr><th class="px-5 py-3 text-left text-xs font-semibold text-slate-500 uppercase">Product</th><th class="px-5 py-3 text-left text-xs font-semibold text-slate-500 uppercase">SKU</th><th class="px-5 py-3 text-right text-xs font-semibold text-slate-500 uppercase">Quantity</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($order->items as $item)<tr><td class="px-5 py-4 font-semibold text-slate-800">{{ $item->product_name }}</td><td class="px-5 py-4 text-slate-500">{{ optional($item->product)->sku_product_id ?? '-' }}</td><td class="px-5 py-4 text-right"><span class="inline-flex min-w-8 justify-center px-2 py-1 rounded-lg bg-slate-100 text-slate-700 font-semibold">{{ $item->quantity }}</span></td></tr>@endforeach</tbody></table></div></div>
    </div>
</div>
@endsection
