@extends('pos.layout.app')

@section('content')
@php($isDelivered = (int) $order->status === 2)
<div class="flex-1 overflow-y-auto bg-slate-50 p-4 md:p-6"><div class="max-w-5xl mx-auto space-y-5">
<div class="flex items-center justify-between gap-4">
    <div><a href="{{ route('pos_product.orders') }}" class="text-sm text-[#128C7E] hover:underline"><i class="fas fa-arrow-left mr-1"></i>Store Orders</a><h1 class="text-2xl font-bold text-slate-800 mt-2">{{ $order->order_number }}</h1><p class="text-sm text-slate-500 mt-1">Created {{ $order->created_at->format('d M Y, h:i A') }}</p></div>
    <div class="text-right">
        <span class="inline-flex px-3 py-1.5 rounded-full text-sm font-semibold {{ $isDelivered ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700' }}">{{ $isDelivered ? 'Delivered' : 'Processing' }}</span>

        @if ($isDelivered)
            <a href="{{ route('pos_product.orders.bill', $order) }}" class="block mt-2 text-sm font-semibold text-[#128C7E] hover:underline"><i class="fas fa-download mr-1"></i>Download Bill</a>
        @endif
    </div>
</div>
<div class="grid grid-cols-1 md:grid-cols-3 gap-5"><div class="bg-white rounded-2xl border border-slate-200 shadow-sm p-5"><p class="text-xs font-semibold text-slate-400 uppercase">Destination Store</p><p class="text-lg font-bold text-slate-800 mt-2">{{ optional($order->store)->name ?? '-' }}</p><p class="text-sm text-slate-500 mt-1">{{ optional($order->store)->address ?? '' }}</p></div><div class="bg-white rounded-2xl border border-slate-200 shadow-sm p-5"><p class="text-xs font-semibold text-slate-400 uppercase">Created By</p><p class="text-lg font-bold text-slate-800 mt-2">{{ optional($order->posUser)->name ?? '-' }}</p><p class="text-sm text-slate-500 mt-1">{{ optional($order->posUser)->email ?? '' }}</p></div><div class="bg-white rounded-2xl border border-slate-200 shadow-sm p-5"><p class="text-xs font-semibold text-slate-400 uppercase">Grand Total</p><p class="text-2xl font-bold text-[#128C7E] mt-2">₹{{ number_format($order->grand_total, 2) }}</p><p class="text-sm text-slate-500 mt-1">{{ $order->items->sum('quantity') }} total quantity</p></div></div>
<div class="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden"><div class="p-5 border-b border-slate-200 flex justify-between items-center"><div><h2 class="text-lg font-bold text-slate-800">Order Items</h2><p class="text-xs text-slate-400 mt-1">Product price is captured at the time of ordering.</p></div><span class="px-3 py-1.5 rounded-full bg-emerald-50 text-[#128C7E] text-xs font-semibold">{{ $order->items->count() }} Items</span></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-50"><tr><th class="px-5 py-3 text-left text-xs font-semibold text-slate-500 uppercase">Product</th><th class="px-5 py-3 text-left text-xs font-semibold text-slate-500 uppercase">SKU</th><th class="px-5 py-3 text-right text-xs font-semibold text-slate-500 uppercase">Price</th><th class="px-5 py-3 text-right text-xs font-semibold text-slate-500 uppercase">Quantity</th><th class="px-5 py-3 text-right text-xs font-semibold text-slate-500 uppercase">Total</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($order->items as $item)<tr><td class="px-5 py-4 font-semibold text-slate-800">{{ $item->product_name }}</td><td class="px-5 py-4 text-slate-500">{{ optional($item->product)->sku_product_id ?? '-' }}</td><td class="px-5 py-4 text-right text-slate-600">₹{{ number_format($item->price, 2) }}</td><td class="px-5 py-4 text-right"><span class="inline-flex min-w-8 justify-center px-2 py-1 rounded-lg bg-slate-100 text-slate-700 font-semibold">{{ $item->quantity }}</span></td><td class="px-5 py-4 text-right font-bold text-[#128C7E]">₹{{ number_format($item->total, 2) }}</td></tr>@endforeach</tbody><tfoot class="bg-slate-50"><tr><td colspan="4" class="px-5 py-4 text-right font-semibold text-slate-700">Grand Total</td><td class="px-5 py-4 text-right font-bold text-[#128C7E]">₹{{ number_format($order->grand_total, 2) }}</td></tr></tfoot></table></div></div>
</div></div>
@endsection
