@extends('layout.app')

@section('content')
@php($isDelivered = (int) $order->status === 2)
<div class="row"><div class="col-12"><div class="card mb-4">
    <div class="card-header pb-0 d-flex justify-content-between align-items-start"><div><a href="{{ route('pos_user.store-order') }}" class="text-sm text-primary"><i class="fas fa-arrow-left me-1"></i>Store Orders</a><h6 class="mt-2 mb-1">{{ $order->order_number }}</h6><p class="text-xs text-secondary mb-0">Created {{ $order->created_at->format('d M Y, h:i A') }}</p></div><div class="text-end"><span class="badge badge-sm {{ $isDelivered ? 'bg-gradient-success' : 'bg-gradient-warning' }}">{{ $isDelivered ? 'Delivered' : 'Processing' }}</span>@if($isDelivered)<br><a href="{{ route('pos_user.store-order.invoice', $order) }}" class="btn btn-sm btn-outline-success mt-2"><i class="fas fa-download me-1"></i>Download Invoice</a>@endif</div></div>
    <div class="card-body"><div class="row mb-4"><div class="col-md-4"><div class="border rounded p-3 h-100"><p class="text-xs text-secondary text-uppercase mb-1">Destination Store</p><h6 class="mb-1">{{ optional($order->store)->name ?? '-' }}</h6><p class="text-xs text-secondary mb-0">{{ optional($order->store)->address ?? '' }}</p></div></div><div class="col-md-4"><div class="border rounded p-3 h-100"><p class="text-xs text-secondary text-uppercase mb-1">Ordered By</p><h6 class="mb-1">{{ optional($order->posUser)->name ?? '-' }}</h6><p class="text-xs text-secondary mb-0">{{ optional($order->posUser)->email ?? '' }}</p></div></div><div class="col-md-4"><div class="border rounded p-3 h-100"><p class="text-xs text-secondary text-uppercase mb-1">Order Amount</p><h5 class="text-success mb-1">₹{{ number_format($order->grand_total, 2) }}</h5><p class="text-xs text-secondary mb-0">{{ $order->items->sum('quantity') }} total quantity</p></div></div></div>
        <div class="d-flex justify-content-between align-items-center mb-3"><h6 class="mb-0">Order Items</h6><form method="POST" action="{{ route('pos_user.store-order.status', $order) }}" class="d-flex gap-2 align-items-center">@csrf<label class="text-xs text-secondary mb-0">Update status</label><select name="status" class="form-select form-select-sm" onchange="this.form.submit()"><option value="1" @selected((int) $order->status === 1)>Processing</option><option value="2" @selected((int) $order->status === 2)>Delivered</option></select></form></div>
        <div class="table-responsive"><table class="table align-items-center mb-0"><thead><tr><th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Product</th><th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">SKU</th><th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 text-end">Price</th><th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 text-end">Qty</th><th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 text-end">Total</th></tr></thead><tbody>@foreach($order->items as $item)<tr><td><p class="text-xs font-weight-bold mb-0">{{ $item->product_name }}</p></td><td><p class="text-xs text-secondary mb-0">{{ optional($item->product)->sku_product_id ?? '-' }}</p></td><td class="text-end"><p class="text-xs mb-0">₹{{ number_format($item->price, 2) }}</p></td><td class="text-end"><p class="text-xs mb-0">{{ $item->quantity }}</p></td><td class="text-end"><p class="text-xs font-weight-bold text-success mb-0">₹{{ number_format($item->total, 2) }}</p></td></tr>@endforeach</tbody><tfoot><tr><td colspan="4" class="text-end"><strong>Grand Total</strong></td><td class="text-end"><strong class="text-success">₹{{ number_format($order->grand_total, 2) }}</strong></td></tr></tfoot></table></div>
    </div>
</div></div></div>
@endsection
